version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
      - MYSQL_DATABASE=zabbix_db
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    restart: always
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
      - MYSQL_DATABASE=zabbix_db
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Tokyo
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
    restart: always
  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=zabbix_db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: