---
zabbix_release_url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu24.04_all.deb"
zabbix_release_dest: /tmp/zabbix-release.deb
zabbix_server_ip: "192.168.1.238"
zabbix_agent_hostname: "web-server"
